insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Kim', 5, 40.0, '173 Buell Trail', '2007-01-18');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Dexter', 4, 97.0, '44442 Sugar Circle', '1962-10-15');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Atwood', 7, 69.8, '265 Loeprich Street', '1974-02-16');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Dryden', 9, 17.9, '6956 Lunder Point', '2003-02-02');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Old Shore', 6, 91.8, '93155 Stang Avenue', '1977-11-25');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Tony', 8, 35.7, '6512 Lukken Trail', '1968-05-29');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Rigney', 10, 72.7, '815 Helena Park', '1983-08-15');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Eliot', 9, 71.7, '6 Hollow Ridge Parkway', '1963-08-13');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Kings', 8, 84.9, '60 Lunder Court', '1968-02-19');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('John Wall', 9, 97.2, '408 Rutledge Avenue', '2005-10-23');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Mandrake', 10, 7.6, '5725 Kings Avenue', '1988-04-21');
insert into management_electric_trains.STATION (station_nm, way_cnt, traffic_flow_cnt, address_txt, repair_dt) values ('Sullivan', 6, 85.8, '9 Bartillon Drive', '2011-09-01');

insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('EXP', 71.5, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 30.72, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('EXP', 37.34, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 23.72, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('EXP', 96.88, false);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 82.67, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 32.94, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('EXP', 65.48, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 43.45, false);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('AIR', 110.31, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 41.63, true);
insert into management_electric_trains.TRIP (departure_type_cd, trip_price_amt, sale_flg) values ('USU', 73.94, true);

insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (5, 'Isabelle', 'Stace', '2019-05-15 22:28:08');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Othilia', 'Howroyd', '2019-04-30 16:06:45');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Ignace', 'Klimkowski', '2019-05-31 20:09:20');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Teddy', 'Burdfield', '2019-04-19 10:08:30');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Marnia', 'Ghost', '2019-05-11 10:36:08');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (5, 'Burk', 'Eymor', '2019-04-23 10:48:59');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (5, 'Carey', 'Postans', '2019-05-22 23:10:38');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Alexander', 'Vinick', '2019-04-27 04:14:54');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Gennifer', 'Rounsefell', '2019-04-28 21:26:53');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Miranda', 'Bullivent', '2019-04-23 05:55:09');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Sasha', 'Dongate', '2019-06-01 11:34:49');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Elmira', 'Ricca', '2019-06-10 14:59:28');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Shanie', 'Dominelli', '2019-02-04 07:08:53');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (4, 'Griffie', 'Impey', '2018-11-11 22:06:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Mandy', 'MacKartan', '2018-12-19 11:23:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Carmela', 'Chedzoy', '2018-05-09 15:22:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Otho', 'Corringham', '2018-04-26 17:23:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Rhonda', 'Lennarde', '2018-05-09 14:28:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (4, 'Johannes', 'Crown', '2018-11-25 20:32:34');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Raine', 'Pumfrey', '2019-05-02 07:09:38');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Ber', 'Treagus', '2018-10-05 18:24:13');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Whitaker', 'Emptage', '2018-09-01 23:20:22');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (5, 'Dorolice', 'Rivel', '2018-08-17 08:34:57');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Irena', 'McIlveen', '2018-10-22 06:18:37');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Hunt', 'Dowsey', '2018-05-08 02:03:29');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Karmen', 'Trew', '2018-05-02 07:17:06');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Gilberta', 'Udie', '2018-10-28 18:27:51');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Tanitansy', 'Nolot', '2018-08-04 15:50:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Ellary', 'Kalderon', '2019-02-28 09:05:54');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Trenna', 'Blackborn', '2018-08-17 20:51:34');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Roldan', 'McRinn', '2019-03-30 16:00:59');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Cash', 'Mealham', '2018-07-12 15:25:32');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Ulrike', 'Mattock', '2018-05-20 17:02:57');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Goran', 'Greasley', '2018-12-31 09:27:43');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Annamarie', 'Fumagallo', '2018-05-13 21:20:27');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Celka', 'Rivallant', '2018-06-06 19:45:36');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Inness', 'Traite', '2019-03-26 01:27:23');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Myranda', 'Loseby', '2018-05-08 11:16:25');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Lindy', 'Montes', '2019-04-07 15:08:35');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Branden', 'Joannic', '2019-02-03 09:54:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Drake', 'Berling', '2018-05-12 23:50:21');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Niki', 'Eustice', '2019-06-01 18:44:53');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Ramsay', 'Welds', '2018-06-15 21:22:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Bondie', 'Pettit', '2019-03-17 17:39:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Thaxter', 'Algy', '2018-05-24 05:42:49');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Buddie', 'Trubshaw', '2018-06-08 14:22:38');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Sammy', 'Bleasdale', '2018-07-11 18:58:30');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Harli', 'Triplett', '2019-04-21 14:34:42');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (7, 'Danella', 'Bellow', '2018-09-11 22:31:43');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Morena', 'Benton', '2019-01-08 20:16:18');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Sibilla', 'Bonnin', '2018-12-03 02:58:44');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Gratia', 'Dodle', '2018-05-20 16:25:23');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Shanie', 'Dominelli', '2019-02-04 07:08:53');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (4, 'Griffie', 'Impey', '2018-11-11 22:06:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Mandy', 'MacKartan', '2018-12-19 11:23:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Carmela', 'Chedzoy', '2018-05-09 15:22:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Otho', 'Corringham', '2018-04-26 17:23:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Rhonda', 'Lennarde', '2018-05-09 14:28:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (4, 'Johannes', 'Crown', '2018-11-25 20:32:34');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Raine', 'Pumfrey', '2019-05-02 07:09:38');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Ber', 'Treagus', '2018-10-05 18:24:13');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Whitaker', 'Emptage', '2018-09-01 23:20:22');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (5, 'Dorolice', 'Rivel', '2018-08-17 08:34:57');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Irena', 'McIlveen', '2018-10-22 06:18:37');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Hunt', 'Dowsey', '2018-05-08 02:03:29');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Karmen', 'Trew', '2018-05-02 07:17:06');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Gilberta', 'Udie', '2018-10-28 18:27:51');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Tanitansy', 'Nolot', '2018-08-04 15:50:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Ellary', 'Kalderon', '2019-02-28 09:05:54');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Trenna', 'Blackborn', '2018-08-17 20:51:34');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Roldan', 'McRinn', '2019-03-30 16:00:59');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Cash', 'Mealham', '2018-07-12 15:25:32');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (3, 'Ulrike', 'Mattock', '2018-05-20 17:02:57');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Goran', 'Greasley', '2018-12-31 09:27:43');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Annamarie', 'Fumagallo', '2018-05-13 21:20:27');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (8, 'Celka', 'Rivallant', '2018-06-06 19:45:36');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Inness', 'Traite', '2019-03-26 01:27:23');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (9, 'Myranda', 'Loseby', '2018-05-08 11:16:25');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Lindy', 'Montes', '2019-04-07 15:08:35');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (11, 'Branden', 'Joannic', '2019-02-03 09:54:16');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (10, 'Drake', 'Berling', '2018-05-12 23:50:21');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Niki', 'Eustice', '2019-06-01 18:44:53');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Ramsay', 'Welds', '2018-06-15 21:22:01');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Bondie', 'Pettit', '2019-03-17 17:39:47');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (2, 'Thaxter', 'Algy', '2018-05-24 05:42:49');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Buddie', 'Trubshaw', '2018-06-08 14:22:38');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Sammy', 'Bleasdale', '2018-07-11 18:58:30');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (6, 'Harli', 'Triplett', '2019-04-21 14:34:42');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (7, 'Danella', 'Bellow', '2018-09-11 22:31:43');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Morena', 'Benton', '2019-01-08 20:16:18');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (12, 'Sibilla', 'Bonnin', '2018-12-03 02:58:44');
insert into management_electric_trains.TICKET (trip_id, buyer_first_nm, buyer_second_nm, purchase_dttm) values (1, 'Gratia', 'Dodle', '2018-05-20 16:25:23');

insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (1, 4, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (1, 10, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (2, 8, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (2, 10, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (3, 5, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (3, 12, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (4, 1, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (4, 7, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (5, 11, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (5, 10, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (6, 3, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (6, 10, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (7, 11, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (7, 5, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (8, 5, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (8, 2, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (9, 1, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (9, 2, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (10, 11, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (10, 7, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (11, 12, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (11, 6, false);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (12, 9, true);
insert into management_electric_trains.TRIP_X_STATION (trip_id, station_id, departure_flg) values (12, 4, false);